package com.dbzbanten.unityadblock

import android.content.Context
import java.io.*

class HostsManager(private val context: Context) {
    
    private val shizukuHelper = ShizukuHelper(context)
    
    // Daftar domain Unity Ads yang akan diblokir
    private val blockedDomains = listOf(
        "unityads.unity3d.com",
        "config.unityads.unity3d.com",
        "auction.unityads.unity3d.com",
        "webview.unityads.unity3d.com",
        "adserver.unityads.unity3d.com",
        "stats.unityads.unity3d.com",
        "tracking.unityads.unity3d.com",
        "events.unityads.unity3d.com",
        "impressions.unityads.unity3d.com",
        "api.unityads.unity3d.com",
        "cdn.unityads.unity3d.com",
        "dsp.unityads.unity3d.com",
        "geolocation.unityads.unity3d.com",
        "httpkafka.unityads.unity3d.com",
        "publisher-config.unityads.unity3d.com",
        "video.unityads.unity3d.com",
        "admediator.unityads.unity3d.com",
        "euw-rtb.unityads.unity3d.com",
        "use-rtb.unityads.unity3d.com",
        "auiopt.unityads.unity3d.com",
        "optout.unityads.unity3d.com",
        "banner.unityads.unity3d.com",
        "analytics.unity3d.com",
        "api.analytics.unity3d.com",
        "cdn.analytics.unity3d.com",
        "events.analytics.unity3d.com",
        "config.analytics.unity3d.com",
        "stats.unity3d.com",
        "perf-events.unity3d.com",
        "unityads-content.unity3d.com",
        "unityads-content-stat.unity3d.com",
        "unityads-content-prd.unity3d.com",
        "unityads-content-cdn.unity3d.com",
        "ironsrc.com",
        "api.ironsrc.com",
        "events.ironsrc.com",
        "logs.ironsrc.com",
        "config.ironsrc.com",
        "init.supersonicads.com",
        "logs.supersonicads.com",
        "events.supersonicads.com",
        "out.supersonicads.com",
        "is-gateway.supersonicads.com",
        "ssacdn.com",
        "cdn.ssacdn.com",
        "applvn.com",
        "applovin.com",
        "rt.applovin.com",
        "res1.applovin.com",
        "res2.applovin.com",
        "googleads.g.doubleclick.net",
        "pagead2.googlesyndication.com",
        "googleadservices.com",
        "admob.com",
        "mintegral.com",
        "vungle.com",
        "adcolony.com",
        "chartboost.com",
        "tapjoy.com",
        "adjust.com",
        "appsflyer.com",
        "kochava.com",
        "singular.net",
        "tenjin.com",
        "gameanalytics.com",
        "firebasecrashlytics.googleapis.com",
        "app-measurement.com"
    )
    
    fun generateHostsContent(): String {
        val sb = StringBuilder()
        sb.append("# Unity Ads Blocker - Generated by DBZBANTEN\n")
        sb.append("# Shizuku Edition - Non Root\n")
        sb.append("127.0.0.1 localhost\n")
        sb.append("::1 localhost\n\n")
        
        blockedDomains.forEach { domain ->
            sb.append("0.0.0.0 $domain\n")
            sb.append("0.0.0.0 www.$domain\n")
        }
        
        return sb.toString()
    }
    
    fun applyHostsViaShizuku(): Boolean {
        return try {
            if (!shizukuHelper.mountSystemWritable()) {
                return false
            }

            if (!shizukuHelper.backupHosts()) {
                return false
            }

            val hostsContent = generateHostsContent()

            if (!shizukuHelper.writeFileWithRoot(
                    "/system/etc/hosts",
                    hostsContent
                )
            ) {
                return false
            }

            true
        } catch (e: Exception) {
            false
        }
    }
    
    fun applyHostsViaVpn(): String {
        // Return hosts content untuk mode VPN (non-root)
        return generateHostsContent()
    }
    
    fun restoreOriginalHosts(): Boolean {
        return shizukuHelper.restoreHosts()
    }
}