plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.dbzbanten.unityadblock'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId 'com.dbzbanten.unityadblock'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file("keystore.jks")

            if (System.getenv("KEYSTORE_PASSWORD") != null) {
                storePassword System.getenv("KEYSTORE_PASSWORD")
            }

            if (System.getenv("KEY_ALIAS") != null) {
                keyAlias System.getenv("KEY_ALIAS")
            }

            if (System.getenv("KEY_PASSWORD") != null) {
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.activity:activity-ktx:1.8.2'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.2'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'

    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
